module.exports = AppConfiguration = {
    USERS_TABLE: 'USERS',
    BOOKING_TABLE: 'BOOKING',
    PAYMENT_TABLE: 'PAYMENT',
    STAFF_TABLE: 'STAFF',
    ROOM_TABLE: 'ROOM',
    EVENT_TABLE: 'EVENT',
    EXPERIENCES_TABLE: 'EXPERIENCES',
}